name: Zadanie1
on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v3

      - name: QEMU set-up
        uses: docker/setup-qemu-action@v2
        
      - name: Buildx set-up
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: malpka8
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ghcr.io/Malpka8/FibCalc
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=docker.io/bszabat5/main:cache
          cache-to: type=registry,ref=docker.io/bszabat5/main:cache
          platforms: linux/arm64,linux/amd64
          context: ./
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}